### ISSUE TITLE
Feature Request - Add a toggle switch to the MCP Servers interface that allows users to turn off or disable mcp servers. 

### ISSUE THREAD

**Issue by qpd-v** [RooVetGit/Roo-Cline#100]
### Which API Provider are you using?

AWS Bedrock

### Which Model are you using?

anthropic.claude-3-5-sonnet-20241022-v2:0

### What happened?

The feature should be somewhere in here:

![395724569-1bc97712-b04d-45f4-b7d8-8c1eb96926ff](https://github.com/user-attachments/assets/98e541e1-bd75-4b0c-aff0-df49d7308ea7)

### Steps to reproduce

1.
2.
3.

**Comment by mrubens** [comment]
Added in #110
