### ISSUE TITLE
Feature Request - Add other models for OpenRouter

### ISSUE THREAD

**Issue by RobertAgee** [RooVetGit/Roo-Cline#112]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

n/a

### What happened?

I'd prefer to try different flagship models through my OpenRouter key (Gemini, ChatGPT, etc), but only Anthropic models are available.

### Steps to reproduce

1. Open Settings
2. Select OpenRouter
3. Only Anthropic models available

### Relevant API REQUEST output

```shell
N/A
```

### Additional context

N/A

**Comment by mrubens** [comment]
@RobertAgee the dropdown is a little confusing to use, but if you clear out the text you will see all models.

<img width="525" alt="Screenshot 2024-12-14 at 2 18 26 PM" src="https://github.com/user-attachments/assets/ded4f9a7-d12f-4dc1-a953-e18674924cd2" />
