### ISSUE TITLE
Feedback text from Roo-Cline is not word-wrapping

### ISSUE THREAD

**Issue by yadah** [RooVetGit/Roo-Cline#123]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Gemini-exp-1206

### What happened?

I sent over a request and as Roo-Cline was working the output printed in one long line.

### Steps to reproduce

1. Make a request
2. Observe output from Roo that is telling the user what it is planning to do
3.

**Comment by syndicate604** [comment]
Roo Output is also not wrapping so goes all the way across screen hard to read

**Comment by mrubens** [comment]
Thanks for reporting this! I'll take a look.

**Comment by mrubens** [comment]
@yadah fix for this is going live now in 2.2.16

**Comment by MuriloFP** [comment]
Test comment content
