### ISSUE TITLE
Code generation happens for new file, then file quickly disappears

### ISSUE THREAD

**Issue by dougbarrett** [RooVetGit/Roo-Cline#131]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

claude-3.5-sonnet:beta

### What happened?

It happens randomly, but sometimes when Cline is attempting to write a new file it will write out the contents of the file and then the file will disappear and then there will be another attempt, which is eating up token costs.  It may take ~5 tries before completing successfully.

Not sure if this is a model issue or a Cline issue

### Steps to reproduce

1. Give a prompt that'd request cline to create new files
2. It will attempt to create a new file
3. You'll see code generate in the diff, and then on completion the file will disappear.

See screenshot to see how it retries - this happens automatically and very quickly
<img width="575" alt="image" src="https://github.com/user-attachments/assets/412911a0-f740-4605-b3a7-cb2a15d20b33" />

### Additional context

It was happening around 6:45 PM pacific time, so again not sure if it's related to usage of the API or any other conditions that may be causing this to happen.

**Comment by dougbarrett** [comment]
What's interesting here, is cline recognized that it was having issues writing the files, so it then figured out it could just write one line of code, save that, and then apply a diff which surprisingly appears to be much more stable.

**Comment by syndicate604** [comment]
This happened to me on Google Gemini 2.0 - it spent 4 million credits for 1  hour trying to edit a 300 line file, over and over diff , full , diff, full , when got back 1 hour later and stopped it, told it to make a NEW file - it could not even save a new file, when done the file closes and dissapears.

**Comment by mrubens** [comment]
> This happened to me on Google Gemini 2.0 - it spent 4 million credits for 1 hour trying to edit a 300 line file, over and over diff , full , diff, full , when got back 1 hour later and stopped it, told it to make a NEW file - it could not even save a new file, when done the file closes and dissapears.

Ugh sorry to hear! The latest version contains a couple improvements for Gemini diff editing. Want to turn on the diff debugging at the bottom of settings and then give it a shot again? Thank you!

**Comment by dougbarrett** [comment]
i appreciate the fast feedback on this! if i run into issue again, i'll try getting some debug info and post it in the thread

**Comment by mrubens** [comment]
Thanks Doug - I pushed some fixes for 2.2.15 as well. I'm going to close this, but please reopen if you're still having issues. Thank you for the help!
