### ISSUE TITLE
Diff appears on unwanted locations

### ISSUE THREAD

**Issue by tanevanwifferen** [RooVetGit/Roo-Cline#146]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

claude 3.5 sonnet

### What happened?

I've had a diff appear on the wrong place 2 out of 2 tries. The first time it appeared between a docstring and the method it belonged to, the second time a new method came somewhere at the end of an existing method, before the closing parenthesis

### Steps to reproduce

1. Try out coding with diffs and sonnet 3.5
2. Maybe it works
3. Maybe it doens't

**Comment by jeremy-returned** [comment]
This is the same issue as #148

**Comment by mrubens** [comment]
Working to release 2.2.14 now - can you test there in 10m or so when it goes live? Make sure to restart VSCode to get the latest. Thank you!

**Comment by mrubens** [comment]
I'm going to close this - can you let me know if this works as expected in 2.2.15 and reopen if not? Thank you for reporting!

**Comment by tanevanwifferen** [comment]
@mrubens everything seems to work perfect now!

**Comment by jeremy-returned** [comment]
I'll second that - seems to be working fine.
