### ISSUE TITLE
write_to_file tool fails when inline comments are detected in code (and sometimes not)

### ISSUE THREAD

**Issue by ryanjoachim** [RooVetGit/Roo-Cline#147]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

**Code suspected of causing the error below:**
```typescript
interface ViewportPriority {
    visible: number      // Currently visible content
    adjacent: number     // Content just outside viewport
    cursor: number       // Content around cursor
    recent: number       // Recently edited content
}
```
### (1)
> [write_to_file for 'proposed_CurrentState.md'] Result:
> The tool execution failed with the following error:
> `<error>`
> Content appears to be truncated. Found comments indicating omitted code (e.g., '// rest of code unchanged', '/* previous code */'). Please provide the complete file content without any omissions if possible, or otherwise use the 'apply_diff' tool to apply the diff to the original file.
> `</error>`

**Next attempt:**
### (2)
> `<thinking>`
> I apologize for any confusion. The content I provided was actually complete - it didn't have any truncated sections or omitted code. Let me try writing the file again with the exact same content.
> `</thinking>`
> 
> `<write_to_file>`
> `<path>proposed_CurrentState.md</path>`

The above steps 1 & 2 are repeated 2x. Then the following starts:

> **Assistant:**
> 
>` <thinking>`
> I notice that the error might be triggered by the inline comments in the ViewportPriority interface. Let me modify those to be more descriptive field names instead of using comments.
> `</thinking>`
> 
>` <write_to_file>`
> `<path>proposed_CurrentState.md</path>`

The suspected culprit is simplified to remove comments:
```typescript
interface ViewportPriority {
    currentlyVisibleContentPriority: number
    adjacentContentPriority: number
    cursorProximityPriority: number
    recentlyEditedPriority: number
}
```

But...then this happens again:

> **User:**
> 
> [write_to_file for 'proposed_CurrentState.md'] Result:
> The tool execution failed with the following error:
> `<error>`
> Content appears to be truncated. Found comments indicating omitted code (e.g., '// rest of code unchanged', '/* previous code */'). Please provide the complete file content without any omissions if possible, or otherwise use the 'apply_diff' tool to apply the diff to the original file.
> `</error>`

Eventually, after a few more attempts, Cline is able to pick an approach that succeeds (by re-reading the file itself to find line numbers). 

I think the original issue _was_ the inline comments, but I looking at its logic I don't think Cline is refreshing a document's line numbers (or context in general) after applying changes - leading it to see and receive conflicting versions of files to work with.

### Steps to reproduce

1. Ask Cline to create a document (.md)
2. Ask it to use either `write_to_file` or `apply_diff` to insert code with inline comments (`// inline comment`) into the new doc
3. Example code:
```typescript
interface ViewportPriority {
    visible: number      // Currently visible content
    adjacent: number     // Content just outside viewport
    cursor: number       // Content around cursor
    recent: number       // Recently edited content
}
```

### Additional context

Related to this issue, it looks like none of those errors/failures are reported in the GUI as errors - just Cline talking to itself.
![image](https://github.com/user-attachments/assets/90302bcb-11ec-42eb-85e6-8187db277b1e)

Not sure if it's working as intended or not, but figured I'd toss it in here too.

**Comment by ryanjoachim** [comment]
Looks like this may be related to (or a dupe of) #131 .

**Comment by mrubens** [comment]
@ryanjoachim any chance you can upload the export of that chat as a gist? I wonder if there's something wrong with https://github.com/RooVetGit/Roo-Cline/blob/eab4a80981c5bf360a1e77e0037b11de3a2dd777/src/integrations/editor/detect-omission.ts#L12

**Comment by mrubens** [comment]
Your code does include "content" in a comment 🤔

**Comment by mrubens** [comment]
I'm not able to easily repro in my unit tests, but I wonder now if it has something to do with the data streaming in and us constantly evaluating this.

**Comment by mrubens** [comment]
I’m going to close this now that #175 is merged. @ryanjoachim can you reopen if it you run into problems again? Thank you!
