### ISSUE TITLE
API request sent too quickly after previous save operation with auto-approve write operations using diffs enabled

### ISSUE THREAD

**Issue by aquabubble** [RooVetGit/Roo-Cline#166]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet 20241022

### What happened?

**What happened:**
After saving code changes, transient TypeScript errors appeared in VS Code before the language server had finished recalculating types. This resulted in temporary issues being listed in Problems, even though the underlying code was valid. Although these errors cleared after a short delay, auto-approve write operations caused Cline to forward these momentary errors to the API prematurely. As a result, the model attempted to fix non-existent issues, leading to a cascade of unnecessary changes and confusion. This problem is particularly evident when editing through diffs is enabled.

**What did you expect to happen:**
Upon saving code changes, Cline should have allowed sufficient time for the language server to recalculate and stabilise prior to sending the next request. This would have prevented transient errors from appearing and eliminated the need for the model to address spurious issues.

### Steps to reproduce

1. Enable auto-approve write operations and diff mode
2. Ask Cline to make some changes in the code base, such as changing an import after refactoring 
3. Cline makes the changes and saves the file
4. Cline sends the result, including "new problems" to the API
5. The model tries to fix the non-existent errors

### Relevant API REQUEST output

```shell
[write_to_file for 'lib/hooks/use-trace.ts'] Result:

The content was successfully saved to lib/hooks/use-trace.ts.

New problems detected after saving the file:
app/traceability/[component]/page.tsx
- [ts Error] Line 12: Property 'requirements' does not exist on type 'void'.
- [ts Error] Line 13: Property 'selectedItems' does not exist on type 'void'.
- [ts Error] Line 14: Property 'traceTargets' does not exist on type 'void'.
- [ts Error] Line 15: Property 'selectedTarget' does not exist on type 'void'.
- [ts Error] Line 16: Property 'setSelectedTarget' does not exist on type 'void'.
- [ts Error] Line 17: Property 'sections' does not exist on type 'void'.
- [ts Error] Line 18: Property 'traceData' does not exist on type 'void'.
- [ts Error] Line 19: Property 'updateTraceData' does not exist on type 'void'.
- [ts Error] Line 20: Property 'saveSelection' does not exist on type 'void'.

<environment_details>
# VSCode Visible Files
lib/hooks/use-trace.ts

# VSCode Open Tabs
lib/hooks/use-trace.ts
```

**Comment by mrubens** [comment]
Thank you for the detailed report! I've been seeing something like that too - explains a lot.

**Comment by mrubens** [comment]
I saw this code in the DiffViewProvider, seems related. I wonder if something I'm missing when applying diffs vs writing the whole file: https://github.com/RooVetGit/Roo-Cline/blob/eab4a80981c5bf360a1e77e0037b11de3a2dd777/src/integrations/editor/DiffViewProvider.ts#L160-L176

**Comment by aquabubble** [comment]
Thanks for the responses. In my case, it was changing the imports during some refactoring. I get the impression that the language server needs some time to fetch the appropriate artefacts from the new imports to then revalidate the code. 

I think it's generally a good approach to only get the deltas in the diagnostics, but with the quick fire changes that auto-approvals create, the strategy does not work so well, since the problems submitted to cline sometimes do change after applying a fix.

If we're in auto-approve write mode, I wonder if we need a slightly different strategy? Sadly it seems that there is no status check on the language server activity so it is likely a "hack" is needed. Perhaps we could wait for problems to stabilise for a short period of time?

**Comment by mrubens** [comment]
> Thanks for the responses. In my case, it was changing the imports during some refactoring. I get the impression that the language server needs some time to fetch the appropriate artefacts from the new imports to then revalidate the code.
> 
> I think it's generally a good approach to only get the deltas in the diagnostics, but with the quick fire changes that auto-approvals create, the strategy does not work so well, since the problems submitted to cline sometimes do change after applying a fix.
> 
> If we're in auto-approve write mode, I wonder if we need a slightly different strategy? Sadly it seems that there is no status check on the language server activity so it is likely a "hack" is needed. Perhaps we could wait for problems to stabilise for a short period of time?

Yeah... I see this in Cline 3.0, probably for this reason https://github.com/cline/cline/blob/b7b5d28bb18f1b8cc8e32a306d00f00976b3eeeb/src/core/Cline.ts#L1233-L1234

**Comment by ryanjoachim** [comment]
I've seen similar issues like this, and someone in Discord had an interesting theory that it happens because a real-time language server is enabled. You can see the linting/language checks updating in the file in real time (no pun intended) as Cline is making edits, and if the error/lint checks can't finish before Cline saves...it's not a crazy theory.

I use _only_ use real-time language servers (same with linting) myself - no "on save" or the like, so I can't easily check that theory...but I figured I'd put it on the radar just in case.

**Comment by mrubens** [comment]
@aquabubble @ryanjoachim thoughts on https://github.com/RooVetGit/Roo-Cline/pull/220?

**Comment by fadenb** [comment]
I experienced the same issue and just increasing the delay after writes did not fix the issue for me.

While I was trying to understand how the components work together I was toying around with Aider. This resulted in the commits you can see here: https://github.com/RooVetGit/Roo-Code/compare/e464c41970dbed4ffc7a9866d752b6db56ce688c...fadenb:Roo-Code:hacky-diagnostics-to-late-fix

Be warned: These changes were fully auto generated while exploring the issue and have not been properly reviewed but I have tested the changed behavior locally and it seems to fully address the issue for me.

Perhaps this is useful as inspiration to someone.
