### ISSUE TITLE
Screenshot quality degradation affects visual analysis accuracy

### ISSUE THREAD

**Issue by libertyteeth** [RooVetGit/Roo-Cline#205]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

When capturing screenshots during browser sessions, Cline is using WebP format with default compression settings, which introduces quality loss. This affects the accuracy of visual analysis in two ways:

1. False Positives: Compression artifacts are misinterpreted as visual defects, causing Cline to report errors in elements that are actually correct.

2. False Negatives: Real visual defects are masked by compression artifacts, causing Cline to miss actual issues that should be detected.

The issue is particularly noticeable with:
- Fine text (< 12px)
- Sharp edges and 1px lines
- Gradient transitions
- Color accuracy checks

### Steps to reproduce

1. Create a test page with precise visual elements:
```html
<!DOCTYPE html>
<html>
<head>
    <style>
        .thin-line { width: 100px; height: 1px; background: #000; }
        .gradient { height: 50px; background: linear-gradient(to right, #fff, #000); }
        .fine-text { font-size: 8px; }
    </style>
</head>
<body>
    <div class="thin-line"></div>
    <div class="gradient"></div>
    <div class="fine-text">Small text for quality testing</div>
</body>
</html>
```

2. Run Cline analysis:
```typescript
const result = await cline.analyzeVisual('test.html');
console.log(result.issues);
```

3. Compare with direct browser screenshot:
   - Open test.html in Chrome
   - Take screenshot manually
   - Notice quality difference in:
     * 1px line (appears blurry in Cline)
     * Gradient (shows banding in Cline)
     * Small text (less readable in Cline)

### Relevant API REQUEST output

```shell
// Current implementation in BrowserSession.ts
let screenshotBase64 = await this.page.screenshot({
    ...options,
    type: "webp", // Uses lossy compression by default
});

// Console output shows compression artifacts:
[Error] Visual analysis failed:
- Element <div class="thin-line"> appears blurred (actual: sharp)
- Gradient shows banding artifacts
- Text element <div class="fine-text"> fails clarity check
```

### Additional context

- Issue affects all screenshot captures
- Reproducible across different browsers and platforms
- Impact increases with:
  * More complex visual elements
  * Finer details in UI
  * Color-sensitive components
  * Text-heavy interfaces

**Environment:**
- Cline Version: 3.0.4
- Puppeteer Version: ^23.4.0
- Node.js Version: 18.x
- OS: Arch Linux

**Proposed Solution:**
Use PNG as primary format for lossless quality, with high-quality WebP as fallback only when needed. This ensures:
- No compression artifacts
- Accurate visual analysis
- Reliable test results
![Screenshot from 2024-12-22 14-40-11](https://github.com/user-attachments/assets/2dc1fb0f-26b3-4d49-afba-b10494e563f5)
![Cline hallucinates what he sees in the browser, then when I give him the image he sees clearly  Guessing there's image compression happening in his browser - Screenshot from 2024-12-22 14-42-52](https://github.com/user-attachments/assets/fb0b1e5c-4397-498f-96d9-39eddc346146)

--

FYI, this is my first contribution to this project (and, I copied this issue from cline/cline as I fixed it yesterday and want to bring the PR over here, as well; I just learned about this project from an AICodeKing video).  I asked Cline to help write this, after reviewing only CONTRIBUTING.md.  Then I asked Cline to review CODE_OF_CONDUCT.md, and zero changes were required: Cline writes positively by default.  Thank you so much for this wonderful creation.

**Comment by mrubens** [comment]
Thank you for fixing this! I deployed your PR https://github.com/RooVetGit/Roo-Cline/pull/208 in release 2.2.27.
