### ISSUE TITLE
"Match precision" option cannot be adjusted

### ISSUE THREAD

**Issue by System233** [RooVetGit/Roo-Cline#257]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

any model

### What happened?

"Match precision" option is always 100%, changes to this option cannot be saved

### Steps to reproduce

1.
2.
3.

**Comment by mrubens** [comment]
Ugh, thanks for the report

**Comment by System233** [comment]
I just observed a new situation. Although the setting always shows 100%, the error message when apply diff fails actually shows the value I want to set.
![image](https://github.com/user-attachments/assets/6de71000-4540-449c-93ba-ed853957d0d1)
![image](https://github.com/user-attachments/assets/b56bc0e4-2b6d-4e94-9c0d-b41642067612)

**Comment by mrubens** [comment]
Very helpful, thank you!

**Comment by mrubens** [comment]
This should fix https://github.com/RooVetGit/Roo-Cline/pull/259

**Comment by System233** [comment]
Thanks, it's awesome!
