### ISSUE TITLE
Sound effects not enabled, but Roo tries to play a sound after each action

### ISSUE THREAD

**Issue by ryanjoachim** [RooVetGit/Roo-Cline#50]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

![image](https://github.com/user-attachments/assets/dd421905-fb96-4aa4-a098-84b28fc9c730)
I don't have a default player for `.wav` files, so Windows 11 spams me with the "Choose an app..." popup - one popup for each action Roo/Cline does.

I can do a screencap too, if that's an easier way to get what I mean.

### Steps to reproduce

1. Update Roo Cline to v2.1.12
2. Uncheck `Enable sound effects` (if it's not already)
3. Ask a question/start a task

**Comment by lloydchang** [comment]
feedback from https://discord.com/channels/1275535550845292637/1275535550845292640/1315443495711936634

Alex. wrote:
> Good idea because its overly unecessary for your average user, if they see a task has been complete, they'll already see it via text
