### ISSUE TITLE
Feature Request: Wrap this in a docker container for safer execution

### ISSUE THREAD

**Issue by byjlw** [RooVetGit/Roo-Cline#84]
I use Cline I kinda want the features you added but it's risky from a computer integrity standpoint auto running system commands. 
Openhands solves this problem but it's expensive to run eating a ton of tokens. 
Having cline take the docker approach of Openhands would be super ideal.

**Comment by lloydchang** [comment]
@byjlw have you tried [GitHub Codespaces](https://docs.github.com/codespaces/getting-started/quickstart)?

**Comment by mrubens** [comment]
@byjlw this is a good idea / discussion - do you mind moving to a feature request here: https://github.com/RooVetGit/Roo-Cline/discussions? As we get more bugs coming in I want to make sure I can clearly delineate. Thank you!

**Comment by mrubens** [comment]
Thank you! Closing in favor of https://github.com/RooVetGit/Roo-Cline/discussions/170
