### ISSUE TITLE
Feature Request: Ability to remove messages from chat history

### ISSUE THREAD

**Issue by qpd-v** [RooVetGit/Roo-Cline#85]
This will help save on token costs if we can somehow delete messages we don't need from the chats. Especially images!

**Comment by CiberNin** [comment]
Someone create a pr for this in cline awhile back. But it was mixed with a bunch of other changes.
Good idea though. There's a good reason all the major AI interfaces let you do this.

**Comment by mrubens** [comment]
@CiberNin @qpd-v do you mind if we move this to https://github.com/RooVetGit/Roo-Cline/discussions so I can separate from the bugs? Would also love a link to that old PR if you have it. This is a good idea. Thank you!

**Comment by qpd-v** [comment]
Added it. Should i close this one?

> @CiberNin @qpd-v do you mind if we move this to https://github.com/RooVetGit/Roo-Cline/discussions so I can separate from the bugs? Would also love a link to that old PR if you have it. This is a good idea. Thank you!

**Comment by mrubens** [comment]
Thank you!
