### ISSUE TITLE
HELP WANTED: DRAFT: merge cline/cline:main to RooVetGit/Roo-Cline:main

### ISSUE THREAD

**Issue by lloydchang** [RooVetGit/Roo-Cline#89]
### Which API Provider are you using?

`saoudrizwan` wrote:
> [It works with any model!](https://discord.com/channels/1275535550845292637/1275535550845292640/1316841355745693716)

### Which Model are you using?

`saoudrizwan` wrote:
> [It works with any model!](https://discord.com/channels/1275535550845292637/1275535550845292640/1316841355745693716)

### What happened?

HELP WANTED: DRAFT: merge `cline/cline:main` to `RooVetGit/Roo-Cline:main`

Related https://github.com/RooVetGit/Roo-Cline/pull/88 https://github.com/RooVetGit/Roo-Cline/issues/89 https://github.com/cline/cline/releases/tag/v2.2.0

### Steps to reproduce

HELP WANTED: DRAFT: merge cline/cline to RooVetGit/Roo-Cline

### Relevant API REQUEST output

To Be Determined

### Additional context
* https://github.com/RooVetGit/Roo-Cline/pull/88
  * https://github.com/RooVetGit/Roo-Cline/pull/88/commits
  * https://github.com/RooVetGit/Roo-Cline/pull/88/checks
  * https://github.com/RooVetGit/Roo-Cline/pull/88/files

**Comment by mrubens** [comment]
Addressed in #93
