### ISSUE TITLE
Feature request: always approve MCP tools

### ISSUE THREAD

**Issue by George5562** [RooVetGit/Roo-Cline#98]
Ideally from an approved list, or else we can just keep approved MCP tools within Roo Cline, and non-approved within Cline.

it would really help flow to have Cline interact with toll as it sees fit.

Also it would be great to be able to specify tool use in a prompt with @

**Comment by mrubens** [comment]
😄

**Comment by mrubens** [comment]
@George5562 Check it out in 2.2.2 and let us know what you think! You have to enable it in the settings.

**Comment by George5562** [comment]
too quick for me, nice one!!
